### ISSUE TITLE
Does not work with vector tiles

### ISSUE THREAD

**Issue by nebulon42** [kosmtik/kosmtik-magnacarto#2]
When using vector tiles with Kosmtik the parser is called twice. Once for the style .tm2 and once for the datasource .tm2source. In the latter case no stylesheet property is present. While carto does not complain about that magnacarto does not like that.

**Comment by nebulon42** [comment]
@yohanboniface I don't know enough about the vector tile workflow to understand this. Why is the stylesheet parser called twice? Is that necessary or could that be changed?

**Comment by yohanboniface** [comment]
>  Why is the stylesheet parser called twice? Is that necessary or could that be changed?

It's expected, in this case there are basically two projects.

> While carto does not complain about that magnacarto does not like that.

One may add a default stylesheet property in the loaded: https://github.com/kosmtik/kosmtik/blob/master/src/back/loader/Base.js#L9

Closing here, let's reopen in kosmtik itself if needed (I prefer to centralize all issues there, it make it easier for everyone I think).
